[package]
name = "eerie-yolo11"
version = "0.1.0"
edition = "2024"

[dependencies]
eerie = { git = "https://github.com/gmmyung/eerie.git" }

image = "0.25.5"
ndarray = "0.16.1"

env_logger = "0.11.7"
