[build]
rustflags = ["-C", "link-arg=-Wl,-rpath,/private/tmp/eerie-yolo11/.venv/lib/python3.12/site-packages/iree/compiler/_mlir_libs/"]
rustdocflags = ["-C", "link-arg=-Wl,-rpath,/private/tmp/eerie-yolo11/.venv/lib/python3.12/site-packages/iree/compiler/_mlir_libs/"]

[env]
LIB_IREE_COMPILER = "/private/tmp/eerie-yolo11/.venv/lib/python3.12/site-packages/iree/compiler/_mlir_libs/"
